### ISSUE TITLE
Zip Files

### ISSUE THREAD

**Issue by richista** [lastship/lastship-common#1]
Hello
I ve tried to install the zip files, but i just get the message, that the structure of the zip files are not correct and the installations stops on openelec 8.0.4
Can you help me?
Thanks
Richi

**Comment by lastship** [comment]
Hi Richi!

Sorry, I can not say, witch Problem you have. I've tested the script.module.urlresolver 4.0.28 and it works
The Struktur in the .zip File is correct.

Today there is an new Version available, so please test this version.
